package com.gmail.chloepika.plugins.debug;
 
import org.bukkit.Bukkit;
import org.bukkit.command.Command;
import org.bukkit.command.CommandSender;
import org.bukkit.event.Listener;
import org.bukkit.plugin.java.JavaPlugin;
 
public class Debug extends JavaPlugin implements Listener
{
public void onEnable()
{
Bukkit.getServer().getPluginManager().registerEvents(this, this);
}
 
public void onDisable()
{
}
 
public boolean onCommand(CommandSender sender, Command command, String label, String[] args)
{
return false;
}
}